/**
 * @file sfcToComponent.ts
 * @description
 * Converts a ParsedSFC into a runnable Nebula component module.
 *
 * This is the final glue step in the SFC pipeline:
 *  - compile <script> -> setup() function
 *  - compile <template> -> IRModule
 *  - attach <meta>, <ai>, <route> blocks
 *  - wrap everything in @terajs/runtime's `component()`
 *  - inject HMR support (dev-only)
 */

import type { ParsedSFC } from "@terajs/sfc";
import { compileScript } from "./compileScript";
import { compileTemplateFromSFC } from "./compileTemplate";

/**
 * Convert a parsed SFC into a full ES module string that exports
 * a Nebula component ready for runtime execution (and HMR in dev).
 */
export function sfcToComponent(sfc: ParsedSFC): string {
  // Extract script content (string or { content })
  const scriptSource =
    typeof sfc.script === "string"
      ? sfc.script
      : sfc.script?.content ?? "";

  // Compile <script> -> setup() function
  const script = compileScript(scriptSource);

  // Compile <template> + meta/ai/route -> IRModule
  const ir = compileTemplateFromSFC(sfc);

  // Component name defaults to filename
  const name = inferComponentName(sfc.filePath);

  // Generate final JS module
  return `
import { component, applyHMRUpdate } from "@terajs/runtime";
import { renderIRModuleToFragment } from "@terajs/renderer-web";

${script.setupCode}

// IRModule for this component
export let ir = ${JSON.stringify(ir, null, 2)};

export { setup };

const Comp = component(
  {
    name: "${name}",
    meta: ir.meta,
    ai: ir.ai,
    route: ir.route
  },
  (props) => {
    const ctx = setup(props);
    return () => renderIRModuleToFragment(ir, ctx);
  }
);

// --- HMR (dev-only) -------------------------------------------------------
if (import.meta.hot) {
  import.meta.hot.accept((mod) => {
    // If script changed, update setup()
    const nextSetup = mod.setup ?? null;

    // If template changed, IR will be regenerated by the bundler
    const nextIR = ir;

    applyHMRUpdate("${name}", nextSetup, nextIR);
  });
}

export default Comp;
`;
}

/**
 * Infer a component name from its file path.
 * Example: "/pages/home.nbl" -> "Home"
 */
function inferComponentName(filePath: string): string {
  const base = filePath.split("/").pop() || "Component";
  return base.replace(/\.\w+$/, "").replace(/[^A-Za-z0-9]/g, "") || "Component";
}

